#include "libftprintf.h"

int ft_printf(const char *ptr, ...);

int main()
{
	int i;
	int j;

	i = ft_printf("s1 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s1 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s2 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*.*d", 10, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s3 %*.*d", 10, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*.*d", -10, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s4 %*.*d", -10, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*.*d", -10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s5 %*.*d", -10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*.*d", -10, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s6 %*.*d", -10, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s7 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s8 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s9 %*.*d", 0, 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s9 %*.*d", 0, 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s10 %*.*d", 10, 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s10 %*.*d", 10, 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s11 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s11 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s12 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s12 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s14 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s14 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s15 %*.*d", 0, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s15 %*.*d", 0, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s16 %*.*d", 0, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s16 %*.*d", 0, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s17 %*.*d", 0, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s17 %*.*d", 0, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s18 %*.*d", 0, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s18 %*.*d", 0, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s19 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s19 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s20 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s20 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s21 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s21 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s22 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s22 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s23 %0*.d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s23 %0*.d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s24 %0*.d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s24 %0*.d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s25 %0*.d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s25 %0*.d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s26 %0*.d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s26 %0*.d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s27 %0*.d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s27 %0*.d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s28 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s28 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s29 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s29 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s30 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s30 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s31 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s31 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s32 %.*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s32 %.*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s33 %.*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s33 %.*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s34 %.*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s34 %.*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s35 %.*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s35 %.*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s36 %.*d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s36 %.*d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s37 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s37 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s38 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s38 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s39 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s39 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s40 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s40 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s41 %*.d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s41 %*.d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s41 %*.d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s41 %*.d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s42 %*.d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s42 %*.d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s43 %*.d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s43 %*.d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s44 %*.d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s44 %*.d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s45 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s45 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s46 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s46 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s47 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s47 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s48 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s48 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s49 %-*.d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s49 %-*.d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s50 %-*.d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s50 %-*.d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s51 %-*.d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s51 %-*.d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s52 %-*.d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s52 %-*.d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s53 %-*.d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s53 %-*.d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s54 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s54 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s55 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s55 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s56 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s56 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s57 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s57 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s58 %-*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s58 %-*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s59 %-*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s59 %-*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s60 %-*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s60 %-*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s61 %-*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s61 %-*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s62 %-*d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s62 %-*d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s63 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s63 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s64 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s64 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s65 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s65 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s66 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s66 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s67 %0*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s67 %0*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s68 %0*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s68 %0*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s69 %0*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s69 %0*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s70 %0*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s70 %0*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s71 %0*d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s71 %0*d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("%0.d", 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("%0.d", 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("99 %015d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("99 %015d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("101 %.5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("101 %.5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("103 %.15d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("103 %.15d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("105 %-5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("105 %-5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("107 %-15d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("107 %-15d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("109 %05d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("109 %05d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("111 %015d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("111 %015d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("113 %.5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("113 %.5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("115 %05d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("115 %05d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("117 %-5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("117 %-5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("119 %-15d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("119 %-15d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("121 %.05d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("121 %.05d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("123 %.000005d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("123 %.000005d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("125 %0.5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("125 %0.5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("127 %00000.5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("127 %00000.5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("129 %.05d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("129 %.05d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("131 %.000005d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("131 %.000005d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("133 %0.5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("133 %0.5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("135 %00000.5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("135 %00000.5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("137 %0d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("137 %0d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("139 %0000d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("139 %0000d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("141 %0d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("141 %0d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("143 %00000d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("143 %00000d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("145 %5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("145 %5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("147 %15d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("147 %15d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("149 %5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("149 %5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("151 %15d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("151 %15d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("153 %00015d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("153 %00015d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("155 %00015d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("155 %00015d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("157 %.00015d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("157 %.00015d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("159 %.00015d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("159 %.00015d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("161 %-.6d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("161 %-.6d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("163 %-.6d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("163 %-.6d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("164 %05.8d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("164 %05.8d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("165 %05.8d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("165 %05.8d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("168 %-5.8d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("168 %-5.8d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("169 %-5.8d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("169 %-5.8d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("170 %06.2d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("170 %06.2d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("171 %06.2d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("171 %06.2d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("176 %02.4d", 128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("176 %02.4d", 128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("177 %02.4d", -128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("177 %02.4d", -128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("178 %06.4d", 128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("178 %06.4d", 128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("179 %06.4d", -128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("179 %06.4d", -128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("180 %08.4d", 128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("180 %08.4d", 128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("181 %08.4d", -128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("181 %08.4d", -128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("66 %-1d%-11d%000000.5d", -128, -9, 333);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("66 %-1d%-11d%000000.5d", -128, -9, 333);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("%d", 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("%d", 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2 %-6.3d", 1231);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("2 %-6.3d", 1231);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3 %-6.8d", 12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("3 %-6.8d", 12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4 %-6.8d", 1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("4 %-6.8d", 1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5 %-5.4d", 1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("5 %-5.4d", 1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6 %-5.6d", 12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("6 %-5.6d", 12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("11 %-6.3d", -12);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("11 %-6.3d", -12);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("22 %-6.3d", -1231);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("22 %-6.3d", -1231);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("33 %-6.8d", -12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("33 %-6.8d", -12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("44 %-6.8d", -1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("44 %-6.8d", -1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("55 %-5.4d", -1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("55 %-5.4d", -1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("66 %-5.6d", -12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("66 %-5.6d", -12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("111 %06.3d", 12);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("111 %06.3d", 12);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("222 %06.3d", 12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("222 %06.3d", 12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("333 %06.8d", 12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("333 %06.8d", 12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("444 %06.8d", 1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("444 %06.8d", 1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("555 %05.4d", 1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("555 %05.4d", 1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("666 %05.6d", 12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("666 %05.6d", 12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("1111 %06.3d", -1);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("1111 %06.3d", -1);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2222 %06.3d", -12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("2222 %06.3d", -12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3333 %06.8d", -12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("3333 %06.8d", -12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4444 %06.8d", -1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("4444 %06.8d", -1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5555 %05.4d", -1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("5555 %05.4d", -1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6666 %05.6d", -12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("6666 %05.6d", -12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("1 %0*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("1 %0*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2 %.*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("2 %.*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3 %*.*d", -0, -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("3 %*.*d", -0, -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4 %-*d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("4 %-*d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5 %-*.d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("5 %-*.d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6 %0*.d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("6 %0*.d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("7 %*.d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("7 %*.d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i1 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i1 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i2 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i2 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i3 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i3 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i4 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i4 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i5 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i5 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i6 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i6 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i7 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i7 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p1 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p1 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p2 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p2 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p3 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p3 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p4 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p4 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p5 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p5 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p6 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p6 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p7 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p7 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y1 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y1 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y2 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y2 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y3 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y3 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y4 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y4 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y5 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y5 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y6 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y6 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y7 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y7 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r1 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r1 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r2 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r2 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r3 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r3 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r4 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r4 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r5 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r5 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r6 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r6 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r7 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r7 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s1 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s1 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*.*d", 10, 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s2 %*.*d", 10, 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s3 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s4 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s5 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s6 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s7 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %*.*d", -10, -10, -6);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s8 %*.*d", -10, -10, -6);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("s9 %*.d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s9 %*.d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("s10 %4.3d", 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s10 %4.3d", 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("1 %4.*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("1 %4.*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("2 %4.*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("2 %4.*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("3 %4.*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("3 %4.*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("4 %4.*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("4 %4.*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("5 %4.*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("5 %4.*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("6 %4.*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("6 %4.*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("7 %4.*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("7 %4.*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("8 %4.*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("8 %4.*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("9 %4.*d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("9 %4.*d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("11 %*.4d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("11 %*.4d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("21 %*.4d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("21 %*.4d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("31 %*.4d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("31 %*.4d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("41 %*.14d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("41 %*.14d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("51 %*.4d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("51 %*.4d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("61 %*.4d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("61 %*.4d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("71 %*.4d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("71 %*.4d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("81 %*.4d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("81 %*.4d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("91 %*.4d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("91 %*.4d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("12 %-*.4d", 0, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("12 %-*.4d", 0, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("22 %-*.4d", 10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("22 %-*.4d", 10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("32 %-*.4d", 10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("32 %-*.4d", 10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("42 %-*.4d", -10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("42 %-*.4d", -10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("52 %-*.4d", -10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("52 %-*.4d", -10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("62 %-*.4d", 0, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("62 %-*.4d", 0, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("72 %-*.4d", 0, -122220);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("72 %-*.4d", 0, -122220);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("82 %-*.4d", 10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("82 %-*.4d", 10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("92 %-*.4d", -10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("92 %-*.4d", -10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("13 %-*.4d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("13 %-*.4d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("23 %-*.4d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("23 %-*.4d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("33 %-*.4d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("33 %-*.4d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("43 %-*.4d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("43 %-*.4d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("53 %-*.4d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("53 %-*.4d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("63 %-*.4d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("63 %-*.4d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("73 %-*.4d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("73 %-*.4d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("83 %-*.4d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("83 %-*.4d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("93 %-*.4d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("93 %-*.4d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("122 %*.4d", 0, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("122 %*.4d", 0, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("222 %*.4d", 10, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("222 %*.4d", 10, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("322 %*.4d", 10, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("322 %*.4d", 10, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("422 %*.4d", -10, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("422 %*.4d", -10, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("522 %*.4d", -10, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("522 %*.4d", -10, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("622 %*.4d", 0, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("622 %*.4d", 0, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("722 %*.4d", 0, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("722 %*.4d", 0, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("822 %*.4d", 10, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("822 %*.4d", 10, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("922 %*.4d", -10, 222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("922 %*.4d", -10, 222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("123 %4.*d", 0, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("123 %4.*d", 0, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("223 %4.*d", 10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("223 %4.*d", 10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("323 %4.*d", 10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("323 %4.*d", 10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("423 %4.*d", -10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("423 %4.*d", -10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("523 %4.*d", -10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("523 %4.*d", -10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("623 %4.*d", 0, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("623 %4.*d", 0, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("723 %4.*d", 0, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("723 %4.*d", 0, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("823 %4.*d", 10, -222222);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("823 %4.*d", 10, -222222);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("923 %4.d++++%01.d", 2222, -12);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("923 %4.d++++%01.d", 2222, -12);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("%dssine", 6);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("%dssine", 6);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("11 %15dXX%10d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("11 %15dXX%10d", 128, 9);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("22 %5dXX%5d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("22 %5dXX%5d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("33 %015dXX%15d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("33 %015dXX%15d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("44 %05dXX%015d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("44 %05dXX%015d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("55 %.15dXX%.3d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("55 %.15dXX%.3d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("66 %.5dXX%.00d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("66 %.5dXX%.00d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("77 %-15dXX%-6d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("77 %-15dXX%-6d", 128, 9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("88 %15dXX%4d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("88 %15dXX%4d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("99 %5dXX%15d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("99 %5dXX%15d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("11 %015dXX%0003d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("11 %015dXX%0003d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("22 %05dXX%00d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("22 %05dXX%00d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("33 %.15dXX%.16d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("33 %.15dXX%.16d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("44 %.5dXX%.06d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("44 %.5dXX%.06d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("66 %-1dXX%-11d%000000.5d", -128, -9, 333);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("66 %-1dXX%-11d%000000.5d", -128, -9, 333);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("77 %.015dXX%.16d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("77 %.015dXX%.16d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("88 %.0000007dXX%.11d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("88 %.0000007dXX%.11d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	printf("------------------------------------------------------\n");
	i = ft_printf("99 %0.10dXX%000000.4d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = ft_printf("99 %0.10dXX%000000.4d", -128, -9);
	printf("%s", "XX\n");
	printf("i is %d\n", j);
	return (0);
}
