/* ************************************************************************** */
/*                                                                            */
/*                                                        |||      ||||||||   */
/*   main.c                                             |+|      |+|    |+|   */
/*                                                    +|+ +|+         +|+     */
/*   By| keuuib <marvin@42.fr>                      +#+  +|+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Createu| 2019/11/20 13|47|43 by keuuib            #+#    #+#             */
/*   Upuateu| 2019/12/08 14|56|54 by keuuib           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libftprintf.h"
int main()
{

	ft_printf("                ==============    MAIN    ============\n");
	ft_printf ("1-----------------------------------\n");
	printf("%u\n", printf("%u", 0));
	printf("%u\n", ft_printf("%u", 0));

	ft_printf("2---------------------\n");

	printf("%u\n", printf("   printf |%u|%u|%u|\n", 115, -12547, 799));
	printf("%u\n", ft_printf("ft_printf |%u|%u|%u|\n", 115, -12547, 799));

	ft_printf("3----------------------\n");

	int mn = -2147483648;
	int mx = 2147483647; 
	printf("%u\n", printf("   printf |%u|%u|\n", mx, mn));
	printf("%u\n", ft_printf("ft_printf |%u|%u|\n", mx, mn));

	ft_printf("4----------------------\n");

	printf("%u\n", printf("   printf |%5u|\n", 5));
	printf("%u\n", ft_printf("ft_printf |%5u|\n", 5));

	ft_printf("5----------------------\n");

	printf("%u\n", printf("   printf |%5u|\n", 55555));
	printf("%u\n", ft_printf("ft_printf |%5u|\n", 55555));

	ft_printf("6----------------------\n");

	printf("%u\n", printf("   printf |%5u|\n", 100000));
	printf("%u\n", ft_printf("ft_printf |%5u|\n", 100000));

	ft_printf("7----------------------\n");
	printf("%u\n", printf("   printf |%10u|%10u|%10u|\n", 5, 12, 178));
	printf("%u\n", ft_printf("ft_printf |%10u|%10u|%10u|\n", 5, 12, 178));
	ft_printf("8----------------------\n");
	printf("%u\n", printf("   printf |%-20u|%-20u|\n", mx, mn));
	printf("%u\n", ft_printf("ft_printf |%-20u|%-20u|\n", mx, mn));
	ft_printf("9----------------------\n");
	printf("%u\n", printf("   printf |%-u|\n", 5));
	printf("%u\n", ft_printf("ft_printf |%-u|\n", 5));
	ft_printf("10----------------------\n");
	printf("%u\n", printf("   printf |%-10u|\n", 5));
	printf("%u\n", ft_printf("ft_printf |%-10u|\n", 5));
	ft_printf("11----------------------\n");
	printf("%u\n", printf("   printf |%5u|\n", 000000));
	printf("%u\n", ft_printf("ft_printf |%5u|\n", 000000));
	ft_printf("12----------------------\n");
	printf("%u\n", printf("   printf |%5u|\n", -5));
	printf("%u\n", ft_printf("ft_printf |%5u|\n", -5));
	ft_printf("13----------------------\n");
	printf("%u\n", printf("   printf |%-5u|\n", -5));
	printf("%u\n", ft_printf("ft_printf |%-5u|\n", -5));
	ft_printf("14----------------------\n");
	printf("%u\n", printf("   printf |%-u|\n", -5));
	printf("%u\n", ft_printf("ft_printf |%-u|\n", -5));
	ft_printf("15----------------------\n");

	printf("%u\n", printf("   printf |%05u|\n", 5));
	printf("%u\n", ft_printf("ft_printf |%05u|\n", 5));
	ft_printf("16----------------------\n");
	printf("%u\n", printf("   printf |%00005u|\n", 5));
	printf("%u\n", ft_printf("ft_printf |%00005u|\n", 5));
	ft_printf("17----------------------\n");
	printf("%u\n", printf("   printf |%050u|\n", 55215));
	printf("%u\n", ft_printf("ft_printf |%050u|\n", 55215));
	ft_printf("18----------------------\n");
	printf("%u\n", printf("   printf |%012u|\n", -5));
	printf("%u\n", ft_printf("ft_printf |%012u|\n", -5));
	ft_printf("19----------------------\n");
	printf("%u\n", printf("   printf |%015u|%015u|\n", mx, mn));
	printf("%u\n", ft_printf("ft_printf |%015u|%015u|\n", mx, mn));
	ft_printf("20----------------------\n");

	printf("%u\n", 	  printf("   printf |%0.6u|%0.6u|\n", -5, 5));
	printf("%u\n", ft_printf("ft_printf |%0.6u|%0.6u|\n", -5, 5));
	ft_printf("21----------------------\n");

	printf("%u\n",    printf("   printf |%5.5u|%5.5u|\n", 12, -12));
	printf("%u\n", ft_printf("ft_printf |%5.5u|%5.5u|\n", 12, -12));
	ft_printf("22----------------------\n");

	printf("%u\n",    printf("   printf |%5.5u|%5.5u|\n", 10324, -10324));
	printf("%u\n", ft_printf("ft_printf |%5.5u|%5.5u|\n", 10324, -10324));
	ft_printf("23----------------------\n");
	printf("%u\n",    printf("   printf |%6.5u|%6.5u|\n", 5, -5));
	printf("%u\n", ft_printf("ft_printf |%6.5u|%6.5u|\n", 5, -5));
	ft_printf("24----------------------\n");
	printf("%u\n",    printf("   printf |%6.5u|%6.5u|\n", 10255, -1025));
	printf("%u\n", ft_printf("ft_printf |%6.5u|%6.5u|\n", 10255, -1025));
	ft_printf("25----------------------\n");
	printf("%u\n",    printf("   printf |%8.5u|%8.3u|\n", 10255, -1025));
	printf("%u\n", ft_printf("ft_printf |%8.5u|%8.3u|\n", 10255, -1025));
	ft_printf("26----------------------\n");
	printf("%u\n",    printf("   printf |%-8.6u|%-8.6u|\n", 1025, -1025));
	printf("%u\n", ft_printf("ft_printf |%-8.6u|%-8.6u|\n", 1025, -1025));
	ft_printf("27----------------------\n");
	printf("%u\n",    printf("   printf |%06.5u|%06.5u|\n", 255, -025));
	printf("%u\n", ft_printf("ft_printf |%06.5u|%06.5u|\n", 255, -025));
	ft_printf("28----------------------\n");
	printf("%u\n",    printf("   printf |%-6.6u|%-6.6u|\n", 255, -255));
	printf("%u\n", ft_printf("ft_printf |%-6.6u|%-6.6u|\n", 255, -525));
	ft_printf("29----------------------\n");
	printf("%u\n",    printf("   printf |%-4.5u|%-4.5u|\n", 255, -025));
	printf("%u\n", ft_printf("ft_printf |%-4.5u|%-4.5u|\n", 255, -025));
	ft_printf("30----------------------\n");
	printf("%u\n",    printf("   printf |%-.5u|%-.5u|\n", 255, -025));
	printf("%u\n", ft_printf("ft_printf |%-.5u|%-.5u|\n", 255, -025));
	ft_printf("31----------------------\n");
	printf("%u\n",    printf("   printf |%-6.1u|%-6.1u|\n", 255, -025));
	printf("%u\n", ft_printf("ft_printf |%-6.1u|%-6.1u|\n", 255, -025));
	ft_printf("32----------------------\n");
	printf("%u\n",    printf("   printf |%06.5u|%06.5u|\n", 255, -025));
	printf("%u\n", ft_printf("ft_printf |%06.5u|%06.5u|\n", 255, -025));
	ft_printf("33----------------------\n");
	printf("%u\n",    printf("   printf |%02u|%02u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%02u|%02u|\n", 100, -100));
	ft_printf ("45-----------------------------------\n");
	printf("%u\n",    printf("   printf |%03u|%03u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%03u|%03u|\n", 100, -100));
	ft_printf ("46-----------------------------------\n");
	printf("%u\n",    printf("   printf |%03u|%03u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%03u|%03u|\n", 100, -100));
	ft_printf ("47-----------------------------------\n");
	printf("%u\n", 	  printf("   printf |%03u|%03u|\n", 255, -100));
	printf("%u\n", ft_printf("ft_printf |%03u|%03u|\n", 255, -100));
	ft_printf ("48-----------------------------------\n");
	printf("%u\n",    printf("   printf |%04u|%02u|\n", 0, 100));
	printf("%u\n", ft_printf("ft_printf |%04u|%02u|\n", 0, 100));
	ft_printf ("49-----------------------------------\n");
	printf("%u\n",    printf("   printf |%04u|%02u|\n", -0, -100));
	printf("%u\n", ft_printf("ft_printf |%04u|%02u|\n", -0, -100));
	ft_printf ("50-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%01ua|a%01ua|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |a%01ua|a%01ua|\n", 0, -0));
	ft_printf ("51-----------------------------------\n");
	printf("%u\n",    printf("   printf |%2.3u|%2.3u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%2.3u|%2.3u|\n", 100, -100));
	ft_printf ("52-----------------------------------\n");
	printf("%u\n",    printf("   printf |%3.3u|%3.3u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%3.3u|%3.3u|\n", 100, -100));
	ft_printf ("53-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%3.3ua|a%3.3ua|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |a%3.3ua|a%3.3ua|\n", 100, -100));
	ft_printf ("54-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.3u|%4.3u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.3u|%4.3u|\n", 100, -100));
	ft_printf ("55-----------------------------------\n");
	printf("%u\n",    printf("   printf |%2.3u|%2.3u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%2.3u|%2.3u|\n", 100, -100));
	ft_printf ("56-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.3u|%4.3u|\n", 0, -1));
	printf("%u\n", ft_printf("ft_printf |%4.3u|%4.3u|\n", 0, -1));
	ft_printf ("57-----------------------------------\n");
	printf("%u\n",    printf("   printf |%1.3u|%1.3u|\n", 0, -1));
	printf("%u\n", ft_printf("ft_printf |%1.3u|%1.3u|\n", 0, -1));
	ft_printf ("58-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%1.3ua|a%1.3ua|\n", 0, -1));
	printf("%u\n", ft_printf("ft_printf |a%1.3ua|a%1.3ua|\n", 0, -1));
	ft_printf ("59-----------------------------------\n");
	printf("%u\n",    printf("   printf |%2.0u|%2.0u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%2.0u|%2.0u|\n", 100, -100));
	ft_printf ("60-----------------------------------\n");
	printf("%u\n",    printf("   printf |%3.0u|%3.0u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%3.0u|%3.0u|\n", 100, -100));
	ft_printf ("61-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%3.0ua|a%3.0ua|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |a%3.0ua|a%3.0ua|\n", 100, -100));
	ft_printf ("62-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.0u|%4.0u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.0u|%4.0u|\n", 100, -100));
	ft_printf ("63-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.0u|%4.0u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.0u|%4.0u|\n", 100, -100));
	ft_printf ("64-----------------------------------\n");
	printf("%u\n",    printf("   printf |%1.0u|%1.0u|\n", 1, -1));
	printf("%u\n", ft_printf("ft_printf |%1.0u|%1.0u|\n", 1, -1));
	ft_printf ("65-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.u|%4.u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.u|%4.u|\n", 100, -100));
	ft_printf ("66-----------------------------------\n");
	printf("%u\n",    printf("   printf |%2.u|%2.u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%2.u|%2.u|\n", 100, -100));
	ft_printf ("67-----------------------------------\n");
	printf("%u\n",    printf("   printf |%3.u|%3.u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%3.u|%3.u|\n", 100, -100));
	ft_printf ("68-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.u|%4.u|\n", 0, -1));
	printf("%u\n", ft_printf("ft_printf |%4.u|%4.u|\n", 0, -1));
	ft_printf ("69-----------------------------------\n");
	printf("%u\n",    printf("   printf |%1.u|%1.u|\n", 0, -1));
	printf("%u\n", ft_printf("ft_printf |%1.u|%1.u|\n", 0, -1));
	ft_printf ("70-----------------------------------\n");
	printf("%u\n",    printf("   printf |%1.0u|%1.0u|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |%1.0u|%1.0u|\n", 0, -0));
	ft_printf ("70.1-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-3.0u|%-1.0u|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |%-3.0u|%-1.0u|\n", 0, -0));
	ft_printf ("71-----------------------------------\n");
	printf("%u\n",    printf("   printf |%2.7u|%2.7u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%2.7u|%2.7u|\n", 100, -100));
	ft_printf ("72-----------------------------------\n");
	printf("%u\n",    printf("   printf |%15.7u|%15.7u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%15.7u|%15.7u|\n", 100, -100));
	ft_printf ("73-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%3.7ua|a%3.7ua|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |a%3.7ua|a%3.7ua|\n", 100, -100));
	ft_printf ("74-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.7u|%4.7u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.7u|%4.7u|\n", 100, -100));
	ft_printf ("75-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.7u|%4.7u|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |%4.7u|%4.7u|\n", 0, -0));
	ft_printf ("76-----------------------------------\n");
	printf("%u\n",    printf("   printf |%1.7u|%1.7u|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |%1.7u|%1.7u|\n", 0, -0));
	ft_printf ("77-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%1.7ua|a%1.7ua|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |a%1.7ua|a%1.7ua|\n", 0, -0));
	ft_printf ("78-----------------------------------\n");
	printf("%u\n",    printf("   printf |%1u|%1u|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |%1u|%1u|\n", 0, -0));
	ft_printf ("79-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%1ua|a%1ua|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |a%1ua|a%1ua|\n", 0, -0));
	ft_printf ("80-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-2u|%-2u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%-2u|%-2u|\n", 100, -100));
	ft_printf ("81-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-3u|%-3u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%-3u|%-3u|\n", 100, -100));
	ft_printf ("82-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.0u|%4.0u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.0u|%4.0u|\n", 100, -100));
	ft_printf ("83-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-4u|%-4u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%-4u|%-4u|\n", 100, -100));
	ft_printf ("84-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-4u|%-4u|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |%-4u|%-4u|\n", 0, -0));
	ft_printf ("85-----------------------------------\n");
	printf("%u\n",    printf("   printf |a%-1ua|a%-1ua|\n", 0, -0));
	printf("%u\n", ft_printf("ft_printf |a%-1ua|a%-1ua|\n", 0, -0));
	ft_printf ("86-----------------------------------\n");
	printf("%u\n",    printf("ft_printf |%.3u|%.3u|\n", 100, -100));
	printf("%u\n", ft_printf("   printf |%.3u|%.3u|\n", 100, -100));
	ft_printf ("87-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.0u|%4.0u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.0u|%4.0u|\n", 100, -100));
	ft_printf ("88-----------------------------------\n");
	printf("%u\n",    printf("   printf |%4.0u|%4.0u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%4.0u|%4.0u|\n", 100, -100));
	ft_printf ("89-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.7u|%.7u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%.7u|%.7u|\n", 100, -100));
	ft_printf ("90-----------------------------------\n");
	printf("%u\n",    printf("   printf |%5.7u|%5.7u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%5.7u|%5.7u|\n", 100, -100));
	ft_printf ("91-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.u|%.u|\n", 100, -100));
	printf("%u\n", ft_printf("ft_printf |%.u|%.u|\n", 100, -100));
	ft_printf ("92-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.u|%.u|\n", 0, 0));
	printf("%u\n", ft_printf("ft_printf |%.u|%.u|\n", 0, -0));
	ft_printf ("93-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.u|%.u|\n", 1, -1));
	printf("%u\n", ft_printf("ft_printf |%.u|%.u|\n", 1, -1));
	ft_printf ("94-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", 1, 0, 0, 0));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", 1, 0, 0, 0));
	ft_printf ("95-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", 1, 1, 1, -1));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", 1, 1, 1, -1));
	ft_printf ("96-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", 5, 0, 5, 12));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", 5, 0, 5, 12));
	ft_printf ("97-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", 5, 1, 5, -1));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", 5, 1, 5, -1));
	ft_printf ("98-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", 10, 100, 10, -100));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", 10, 100, 10, -100));
	ft_printf ("99-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", -5, 100, -5, -100));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", -5, 100, -5, -100));
	ft_printf ("100-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", -10, 100000, -10, -100000));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", -10, 100000, -10, -100000));
	ft_printf ("101-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n", -15, 100000, -15, -100000));
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n", -15, 100000, -15, -100000));
	ft_printf ("102-----------------------------------\n");

	ft_printf ("103-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", 0, 0, 0, 1));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", 0, 0, 0, 1));
	ft_printf ("104-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", 0, -1, 1, -1));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", 0, -1, 1, -1));
	ft_printf ("105-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", 5, 1, 5, -1));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", 5, 1, 5, -1));
	ft_printf ("106-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", 5, 0, 5, -0));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", 5, 0, 5, -0));
	ft_printf ("107-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*u|%*u|\n",  1, 0, 1, 1));  
	printf("%u\n", ft_printf("ft_printf |%*u|%*u|\n",  1, 0, 1, 1));
	ft_printf ("103-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", 0, 0, 0, 1));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", 0, 0, 0, 1));
	ft_printf ("104-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", 0, -1, -1, -1));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", 0, -1, -1, -1));
	ft_printf ("105-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", -5, 1, -5, -1));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", -5, 1, -5, -1));
	ft_printf ("106-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n", -5, 0, -5, -0));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n", -5, 0, -5, -0));
	ft_printf ("108-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n",  5, 100, 5, -100));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n",  5, 100, 5, -100));
	ft_printf ("109-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n",  -5, 10100, -5, -1010));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n",  -5, 10100, -5, -1010));
	ft_printf ("110-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n",  3, 10012, 3, -10012));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n",  3, 10012, 3, -10012));
	ft_printf ("111-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*u|%0*u|\n",  -3, 10012, -3, -10012));
	printf("%u\n", ft_printf("ft_printf |%0*u|%0*u|\n",  -3, 10012, -3, -10012));
	ft_printf ("112-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.*u|%.*u|\n", 0, 0, 5, -1));
	printf("%u\n", ft_printf("ft_printf |%.*u|%.*u|\n", 0, 0, 5, -1));
	ft_printf ("113-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.*u|%.*u|\n", -5, 1, -5, -1));
	printf("%u\n", ft_printf("ft_printf |%.*u|%.*u|\n", -5, 1, -5, -1));
	ft_printf ("114-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.*u|%.*u|\n", 5, 0, 5, -0));
	printf("%u\n", ft_printf("ft_printf |%.*u|%.*u|\n", 5, 0, 5, -0));
	ft_printf ("115-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.*u|%.*u|\n",  5, 100, 5, -100));
	printf("%u\n", ft_printf("ft_printf |%.*u|%.*u|\n",  5, 100, 5, -100));
	ft_printf ("116-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.*u|%.*u|\n",  -5, 10100, 15, -1010));
	printf("%u\n", ft_printf("ft_printf |%.*u|%.*u|\n",  -5, 10100, 15, -1010));
	ft_printf ("117-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.*u|%.*u|\n",  3, 10012, -3, -10012));
	printf("%u\n", ft_printf("ft_printf |%.*u|%.*u|\n",  3, 10012, -3, -10012));
	ft_printf ("118-----------------------------------\n");
	printf("%u\n",    printf("   printf |%.*u|%.*u|\n",  0, 10012, 0, -10012));
	printf("%u\n", ft_printf("ft_printf |%.*u|%.*u|\n",  0, 10012, 0, -10012));
	ft_printf ("118-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n",  -3, 10012, -3, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n",  -3, 10012, -3, -10012));
	ft_printf ("119-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n",  5, 10012, 5, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n",  5, 10012, 5, -10012));
	ft_printf ("120-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n",  -5, 10012, -5, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n",  -5, 10012, -5, -10012));
	ft_printf ("121-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n", 0, 0, 0, 0));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n", 0, 0, 0, 0));
	ft_printf ("122-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n", -5, 1, -5, -1));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n", -5, 1, -5, -1));
	ft_printf ("123-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n", 5, 0, 5, -0));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n", 5, 0, 5, -0));
	ft_printf ("124-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n",  5, 100, 5, -100));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n",  5, 100, 5, -100));
	ft_printf ("125-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n",  -5, 10100, 15, -1010));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n",  -5, 10100, 15, -1010));
	ft_printf ("126-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n",  20, 10012, 20, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n",  20, 10012, 20, -10012));
	ft_printf ("127-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*u|%-*u|\n",  -20, 10012, -20, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*u|%-*u|\n",  -20, 10012, -20, -10012));
	ft_printf ("128-----------------------------------\n");	
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  -3, 10012, -3, -10012));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  -3, 10012, -3, -10012));
	ft_printf ("129-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  5, 10012, 5, -10012));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  5, 10012, 5, -10012));
	ft_printf ("130-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  -5, 10012, -5, -10012));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  -5, 10012, -5, -10012));
	ft_printf ("131-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n", 0, 0, 0, 0));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n", 0, 0, 0, 0));
	ft_printf ("132-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n", -5, 1, -5, -1));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n", -5, 1, -5, -1));
	ft_printf ("133-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n", 5, 0, 5, -0));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n", 5, 0, 5, -0));
	ft_printf ("134-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  5, 100, 5, -100));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  5, 100, 5, -100));
	ft_printf ("135-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  -5, 10100, 15, -1010));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  -5, 10100, 15, -1010));
	ft_printf ("136-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  20, 10012, 20, -10012));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  20, 10012, 20, -10012));
	ft_printf ("137-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  -20, 10012, -20, -10012));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  -20, 10012, -20, -10012));
	ft_printf ("138-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.u|%0*.u|\n",  -3, 10012, -3, -1010));
	printf("%u\n", ft_printf("ft_printf |%0*.u|%0*.u|\n",  -3, 10012, -3, -1010));
	ft_printf ("139-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n",  5, 10012, 5, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n",  5, 10012, 5, -10012));
	ft_printf ("140-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n",  -5, 10012, -5, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n",  -5, 10012, -5, -10012));
	ft_printf ("141-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n", 0, 0, -2, 0));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n", 0, 0, -2, 0));
	ft_printf ("142-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n", -5, 1, -5, -1));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n", -5, 1, -5, -1));
	ft_printf ("143-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n", 5, 0, 5, -0));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n", 5, 0, 5, -0));
	ft_printf ("144-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n",  5, 100, 5, -100));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n",  5, 100, 5, -100));
	ft_printf ("145-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n",  -5, 10100, 15, -1010));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n",  -5, 10100, 15, -1010));
	ft_printf ("146-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n",  20, 10012, 20, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n",  20, 10012, 20, -10012));
	ft_printf ("147-----------------------------------\n");
	printf("%u\n",    printf("   printf |%-*.u|%-*.u|\n",  -20, 10012, -20, -10012));
	printf("%u\n", ft_printf("ft_printf |%-*.u|%-*.u|\n",  -20, 10012, -20, -10012));
	ft_printf ("149-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n", -1, 1, 5, 1, 1, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n", -1, 1, 5, 1, 1, -5));
	ft_printf ("150-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  0, 0, 5, 0, 0, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  0, 0, 5, 0, 0, -5));
	ft_printf ("151-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  -1, -1, 5, -1, -1, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  -1, -1, 5, -1, -1, -5));
	ft_printf ("152-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n", -5, -5, 5, -5, -5, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n", -5, -5, 5, -5, -5, -5));
	ft_printf ("153-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n", 2, 2, 500, 2, 2, -500));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n", 2, 2, 500, 2, 2, -500));
	ft_printf ("154-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  -2, -2, 500, -2, -2, -500));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  -2, -2, 500, -2, -2, -500));
	ft_printf ("155-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  5, 5, 0, 5, 5, 0));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  5, 5, 0, 5, 5, 0));
	ft_printf ("156-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  0, 0, 0, 0, 0, 5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  0, 0, 0, 0, 0, 5));
	ft_printf ("157-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  5, 3, 5, 5, 3, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  5, 3, 5, 5, 3, -5));
	ft_printf ("158-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  -5, 3, 5, -5, 3, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  -5, 3, 5, -5, 3, -5));
	ft_printf ("159-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  3, 4, 5, 5, 4, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  3, 4, 5, 3, 4, -5));
	ft_printf ("160-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  -2, 4, 5, -2, 4, -5));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  -2, 4, 5, -2, 4, -5));
	ft_printf ("161-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|%*.*u|\n",  3, 2, 5000, 3, 2, -5000));
	printf("%u\n", ft_printf("ft_printf |%*.*u|%*.*u|\n",  3, 2, 5000, 3, 2, -5000));
	ft_printf ("162-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.*u|%*.*u|\n",  5, 15, 50000, 5, 15, -50000));
	printf("%u\n", ft_printf("ft_printf |%0*.*u|%*.*u|\n",  5, 15, 50000, 5, 15, -50000));
	ft_printf ("163-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.*u|%*.*u|\n", 15, 5, 500000, 15, 5, -500000));
	printf("%u\n", ft_printf("ft_printf |%0*.*u|%*.*u|\n", 15, 5, 500000, 15, 5, -500000));
	ft_printf ("164-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.*u|%015.5u|\n", 15, -5, 50, 50));
	printf("%u\n", ft_printf("ft_printf |%0*.*u|%015.5u|\n", 15, -5, 50, 50));
	ft_printf ("170-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.10u|%*.10u|\n", 15, 50, 15, -50));
	printf("%u\n", ft_printf("ft_printf |%*.10u|%*.10u|\n", 15, 50, 15, -50));
	ft_printf ("165-----------------------------------\n");
	printf("%u\n",    printf("   printf |%012.*u|\n", 10, 15));
	printf("%u\n", ft_printf("ft_printf |%012.*u|\n", 10, 15));
	ft_printf ("165-----------------------------------\n");
	printf("%u\n",    printf("   printf |%*.*u|\n", 0, 0, 0));
	printf("%u\n", ft_printf("ft_printf |%*.*u|\n", 0, 0, 0));
	ft_printf ("169-----------------------------------\n");
	printf("%u\n",    printf("   printf |%0*.*u|%0*.*u|\n", 8, 5, 50, -8, 5, -50));
	printf("%u\n", ft_printf("ft_printf |%0*.*u|%0*.*u|\n", 8, 5, 50, -8, 5, -50));

	return 0;
}
