#include "libftprintf.h"

int ft_printf(const char *ptr, ...);

int main()
{
	int i;

	i = -15248523;

	printf("s1 %d\n", i);
	printf("number is %-5X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	printf("s1 %d\n", i);
	printf("number is %X\n", i);
	i = i + 1;
	printf("-------------------------------------------------\n");
	return (0);
}
