/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: yhadari <yhadari@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2019/12/01 22:31:28 by yhadari           #+#    #+#             */
/*   Updated: 2019/12/05 22:01:27 by yhadari          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libftprintf.h"

int ft_printf(const char *ptr, ...);

int main()
{
	int i;
	int j;

	/*i = ft_printf("%0.d", 0);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("%0.d", 0);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("99 %015d", 128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("99 %015d", 128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("101 %.5d", 128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("101 %.5d", 128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("103 %.15d", 128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("103 %.15d", 128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("105 %-5d", 128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("105 %-5d", 128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("107 %-15d", 128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("107 %-15d", 128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("109 %05d", -128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("109 %05d", -128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("111 %015d", -128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("111 %015d", -128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("113 %.5d", -128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("113 %.5d", -128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("115 %05d", -128);
	  printf("%s", "XX\n");
	  printf("i is %d\n", i);
	  j = printf("115 %05d", -128);
	  printf("%s", "XX\n");
	  printf("j is %d\n", j);
	  printf("--------------------------------------------------\n");
	  i = ft_printf("117 %-5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("117 %-5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("119 %-15d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("119 %-15d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("121 %.05d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("121 %.05d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("123 %.000005d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("123 %.000005d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("125 %0.5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("125 %0.5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("127 %00000.5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("127 %00000.5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("129 %.05d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("129 %.05d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("131 %.000005d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("131 %.000005d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("133 %0.5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("133 %0.5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("135 %00000.5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("135 %00000.5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("137 %0d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("137 %0d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("139 %0000d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("139 %0000d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("141 %0d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("141 %0d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("143 %00000d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("143 %00000d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("145 %5d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("145 %5d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("147 %15d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("147 %15d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("149 %5d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("149 %5d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("151 %15d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("151 %15d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("153 %00015d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("153 %00015d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("155 %00015d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("155 %00015d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("157 %.00015d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("157 %.00015d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("159 %.00015d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("159 %.00015d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("161 %-.6d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("161 %-.6d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("163 %-.6d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("163 %-.6d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("164 %05.8d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("164 %05.8d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("165 %05.8d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("165 %05.8d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("168 %-5.8d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("168 %-5.8d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("169 %-5.8d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("169 %-5.8d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("170 %06.2d", -128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("170 %06.2d", -128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("171 %06.2d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("171 %06.2d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("176 %02.4d", 128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("176 %02.4d", 128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("177 %02.4d", -128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("177 %02.4d", -128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("178 %06.4d", 128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("178 %06.4d", 128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("179 %06.4d", -128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("179 %06.4d", -128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("180 %08.4d", 128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("180 %08.4d", 128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("181 %08.4d", -128123);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("181 %08.4d", -128123);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("66 %-1d%-11d%000000.5d", -128, -9, 333);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("66 %-1d%-11d%000000.5d", -128, -9, 333);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("%d", 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("%d", 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2 %-6.3d", 1231);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("2 %-6.3d", 1231);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3 %-6.8d", 12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("3 %-6.8d", 12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4 %-6.8d", 1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("4 %-6.8d", 1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5 %-5.4d", 1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("5 %-5.4d", 1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6 %-5.6d", 12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("6 %-5.6d", 12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("11 %-6.3d", -12);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("11 %-6.3d", -12);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("22 %-6.3d", -1231);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("22 %-6.3d", -1231);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("33 %-6.8d", -12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("33 %-6.8d", -12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("44 %-6.8d", -1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("44 %-6.8d", -1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("55 %-5.4d", -1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("55 %-5.4d", -1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("66 %-5.6d", -12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("66 %-5.6d", -12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("111 %06.3d", 12);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("111 %06.3d", 12);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("222 %06.3d", 12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("222 %06.3d", 12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("333 %06.8d", 12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("333 %06.8d", 12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("444 %06.8d", 1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("444 %06.8d", 1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("555 %05.4d", 1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("555 %05.4d", 1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("666 %05.6d", 12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("666 %05.6d", 12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("1111 %06.3d", -1);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("1111 %06.3d", -1);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2222 %06.3d", -12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("2222 %06.3d", -12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3333 %06.8d", -12312);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("3333 %06.8d", -12312);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4444 %06.8d", -1231281230);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("4444 %06.8d", -1231281230);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5555 %05.4d", -1231281);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("5555 %05.4d", -1231281);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6666 %05.6d", -12312812);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("6666 %05.6d", -12312812);
	printf("%s", "XX\n");
	printf("j is %d\n", j);*/
		printf("-------------------------------------------------\n");
	i = ft_printf("1 %0*d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("1 %0*d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2 %.*d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("2 %.*d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3 %*.*d", -0, -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("3 %*.*d", -0, -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4 %-*d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("4 %-*d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5 %-*.d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("5 %-*.d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6 %0*.d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("6 %0*.d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("7 %*.d", -0, -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("7 %*.d", -0, -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i1 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i1 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i2 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i2 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i3 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i3 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i4 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i4 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i5 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i5 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i6 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i6 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i7 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("i7 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p1 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p1 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p2 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p2 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p3 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p3 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p4 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p4 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p5 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p5 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p6 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p6 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p7 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("p7 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y1 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y1 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y2 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y2 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y3 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y3 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y4 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y4 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y5 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y5 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y6 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y6 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y7 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("y7 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r1 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r1 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r2 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r2 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r3 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r3 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r4 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r4 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r5 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r5 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r6 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r6 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r7 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("r7 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s1 %*.*d", -10, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s1 %*.*d", -10, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s2 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s3 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*.*d", 10, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s4 %*.*d", 10, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*.*d", -10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s5 %*.*d", -10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*.*d", -10, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s6 %*.*d", -10, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s7 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("161 %-.6d", 128);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("161 %-.6d", 128);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("163 %-.6d", -0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("163 %-.6d", -0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("--------------------------------------------------\n");
	return (0);
}
