/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: yhauari <marvin@42.fr>                     +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Createu: 2019/12/18 18:16:45 by yhauari           #+#    #+#             */
/*   upuateu: 2019/12/19 02:13:26 by yhauari          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "libftprintf.h"

int ft_printf(const char *ptr, ...);

int main()
{	int i;
	int j;

	i = 0;
	j = 0;
	i = ft_printf("%0.u", 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("%0.u", 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("99 %015u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("99 %015u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("101 %.5u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("101 %.5u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("103 %.15u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("103 %.15u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("105 %-5u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("105 %-5u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("107 %-15u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("107 %-15u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("109 %05u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("109 %05u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("111 %015u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("111 %015u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("113 %.5u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("113 %.5u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("115 %05u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("115 %05u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("117 %-5u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("117 %-5u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("119 %-15u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("119 %-15u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("121 %.05u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("121 %.05u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("123 %.000005u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("123 %.000005u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("125 %0.5u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("125 %0.5u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("127 %00000.5u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("127 %00000.5u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("129 %.05u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("129 %.05u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("131 %.000005u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("131 %.000005u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("133 %0.5u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("133 %0.5u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("135 %00000.5u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("135 %00000.5u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("137 %0u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("137 %0u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("139 %0000u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("139 %0000u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("141 %0u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("141 %0u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("143 %00000u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("143 %00000u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("145 %5u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("145 %5u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("147 %15u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("147 %15u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("149 %5u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("149 %5u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("151 %15u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("151 %15u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("153 %00015u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("153 %00015u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("155 %00015u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("155 %00015u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("157 %.00015u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("157 %.00015u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("159 %.00015u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("159 %.00015u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("161 %-.6u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("161 %-.6u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("163 %-.6u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("163 %-.6u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("164 %05.8u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("164 %05.8u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("165 %05.8u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("165 %05.8u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("168 %-5.8u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("168 %-5.8u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("169 %-5.8u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("169 %-5.8u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("170 %06.2u", -128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("170 %06.2u", -128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("171 %06.2u", 128);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("171 %06.2u", 128);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("176 %02.4u", 128123);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("176 %02.4u", 128123);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("177 %02.4u", -128123);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("177 %02.4u", -128123);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("178 %06.4u", 128123);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("178 %06.4u", 128123);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("179 %06.4u", -128123);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("179 %06.4u", -128123);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("180 %08.4u", 128123);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("180 %08.4u", 128123);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("181 %08.4u", -128123);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("181 %08.4u", -128123);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("66 %-1u%-15u%000000.5u", -128, -9, 333);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("66 %-1u%-15u%000000.5u", -128, -9, 333);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("%u", 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("%u", 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2 %-6.3u", 1231);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("2 %-6.3u", 1231);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3 %-6.8u", 12312);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("3 %-6.8u", 12312);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4 %-6.8u", 1231281230);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("4 %-6.8u", 1231281230);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5 %-5.4u", 1231281);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("5 %-5.4u", 1231281);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6 %-5.6u", 12312812);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("6 %-5.6u", 12312812);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("11 %-6.3u", -12);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("11 %-6.3u", -12);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("22 %-6.3u", -1231);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("22 %-6.3u", -1231);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("33 %-6.8u", -12312);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("33 %-6.8u", -12312);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("44 %-6.8u", -1231281230);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("44 %-6.8u", -1231281230);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("55 %-5.4u", -1231281);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("55 %-5.4u", -1231281);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("66 %-5.6u", -12312812);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("66 %-5.6u", -12312812);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("111 %06.3u", 12);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("111 %06.3u", 12);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("222 %06.3u", 12312);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("222 %06.3u", 12312);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("333 %06.8u", 12312);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("333 %06.8u", 12312);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("444 %06.8u", 1231281230);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("444 %06.8u", 1231281230);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("555 %05.4u", 1231281);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("555 %05.4u", 1231281);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("666 %05.6u", 12312812);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("666 %05.6u", 12312812);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("1111 %06.3u", -1);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("1111 %06.3u", -1);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2222 %06.3u", -12312);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("2222 %06.3u", -12312);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3333 %06.8u", -12312);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("3333 %06.8u", -12312);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4444 %06.8u", -1231281230);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("4444 %06.8u", -1231281230);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5555 %05.4u", -1231281);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("5555 %05.4u", -1231281);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6666 %05.6u", -12312812);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("6666 %05.6u", -12312812);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("1 %0*u", 0, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("1 %0*u", 0, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("2 %.*u", 0, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("2 %.*u", 0, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("3 %*.*u", -0, -0, -0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("3 %*.*u", -0, -0, -0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("4 %-*u", -0, -0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("4 %-*u", -0, -0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("5 %-*.u", -0, -0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("5 %-*.u", -0, -0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("6 %0*.u", -0, -0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("6 %0*.u", -0, -0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("7 %*.u", -0, -0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("7 %*.u", -0, -0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i1 %0*u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i1 %0*u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i2 %.*u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i2 %.*u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i3 %*.*u", 10, 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i3 %*.*u", 10, 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i4 %-*u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i4 %-*u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i5 %-*.u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i5 %-*.u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i6 %0*.u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i6 %0*.u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("i7 %*.u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i7 %*.u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p1 %0*u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("p1 %0*u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p2 %.*u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("p2 %.*u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p3 %*.*u", 10, 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("p3 %*.*u", 10, 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p4 %-*u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("p4 %-*u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p5 %-*.u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("p5 %-*.u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p6 %0*.u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("p6 %0*.u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("p7 %*.u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("p7 %*.u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y1 %0*u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("y1 %0*u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y2 %.*u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("y2 %.*u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y3 %*.*u", -10, -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("y3 %*.*u", -10, -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y4 %-*u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("y4 %-*u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y5 %-*.u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("y5 %-*.u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y6 %0*.u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("y6 %0*.u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("y7 %*.u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("y7 %*.u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r1 %0*u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("r1 %0*u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r2 %.*u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("r2 %.*u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r3 %*.*u", 10, -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("r3 %*.*u", 10, -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r4 %-*u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("r4 %-*u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r5 %-*.u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("r5 %-*.u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r6 %0*.u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("r6 %0*.u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("r7 %*.u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("r7 %*.u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s1 %*.*u", -10, -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s1 %*.*u", -10, -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*.*u", 10, 10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s2 %*.*u", 10, 10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*.*u", -10, -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s3 %*.*u", -10, -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*.*u", 10, -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s4 %*.*u", 10, -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*.*u", -10, 10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s5 %*.*u", -10, 10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*.*u", -10, 10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s6 %*.*u", -10, 10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*.*u", 10, -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s7 %*.*u", 10, -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %*.*u", -10, -10, -6);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s8 %*.*u", -10, -10, -6);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("s9 %*.u", -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s9 %*.u", -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("s10 %4.3u", 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s10 %4.3u", 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("1 %4.*u", 0, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("1 %4.*u", 0, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("2 %4.*u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("2 %4.*u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("3 %4.*u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("3 %4.*u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("4444 %4.*u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("4444 %4.*u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("5 %4.*u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("5 %4.*u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("6 %4.*u", 0, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("6 %4.*u", 0, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("7 %4.*u", 0, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("7 %4.*u", 0, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("8 %4.*u", 10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("8 %4.*u", 10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("999 %4.*u", -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("999 %4.*u", -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("11 %*.4u", 0, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("11 %*.4u", 0, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("221 %*.4u", 12, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("221 %*.4u", 12, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("31 %*.4u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("31 %*.4u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("41 %*.14u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("41 %*.14u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("51 %*.4u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("51 %*.4u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("61 %*.4u", 0, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("61 %*.4u", 0, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("71 %*.4u", 0, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("71 %*.4u", 0, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("81 %*.4u", 10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("81 %*.4u", 10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("91 %*.4u", -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("91 %*.4u", -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("12 %-*.4u", 0, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("12 %-*.4u", 0, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("22 %-*.4u", 10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("22 %-*.4u", 10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("32 %-*.4u", 10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("32 %-*.4u", 10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("42 %-*.4u", -10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("42 %-*.4u", -10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("52 %-*.4u", -10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("52 %-*.4u", -10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("62 %-*.4u", 0, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("62 %-*.4u", 0, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("72 %-*.4u", 0, -122220);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("72 %-*.4u", 0, -122220);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("82 %-*.4u", 10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("82 %-*.4u", 10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("92 %-*.4u", -10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("92 %-*.4u", -10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("13 %-*.4u", 0, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("13 %-*.4u", 0, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("23 %-*.4u", 10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("23 %-*.4u", 10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("33 %-*.4u", 10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("33 %-*.4u", 10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("43 %-*.4u", -10, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("43 %-*.4u", -10, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("53 %-*.4u", -10, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("53 %-*.4u", -10, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("63 %-*.4u", 0, 10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("63 %-*.4u", 0, 10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("73 %-*.4u", 0, -10);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("73 %-*.4u", 0, -10);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("83 %-*.4u", 10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("83 %-*.4u", 10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("93 %-*.4u", -10, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("93 %-*.4u", -10, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("122 %*.4u", 0, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("122 %*.4u", 0, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("222 %*.4u", 10, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("222 %*.4u", 10, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("322 %*.4u", 10, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("322 %*.4u", 10, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("422 %*.4u", -10, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("422 %*.4u", -10, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("522 %*.4u", -10, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("522 %*.4u", -10, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("622 %*.4u", 0, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("622 %*.4u", 0, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("722 %*.4u", 0, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("722 %*.4u", 0, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("822 %*.4u", 10, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("822 %*.4u", 10, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("922 %*.4u", -10, 222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("922 %*.4u", -10, 222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("123 %4.*u", 0, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("123 %4.*u", 0, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("223 %4.*u", 10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("223 %4.*u", 10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("323 %4.*u", 10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("323 %4.*u", 10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("423 %4.*u", -10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("423 %4.*u", -10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("523 %4.*u", -10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("523 %4.*u", -10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("623 %4.*u", 0, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("623 %4.*u", 0, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("723 %4.*u", 0, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("723 %4.*u", 0, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("823 %4.*u", 10, -222222);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("823 %4.*u", 10, -222222);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("923 %-3.u", -1);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("923 %-3.u", -1);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("i923 %-3.1u", 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("i923 %-3.1u", 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("924 %-4.u", -1);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("924 %-4.u", -1);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("925 %1.3u%1.4u", -1, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("925 %1.3u%1.4u", -1, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("926 %0.0u", -1);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("926 %0.0u", -1);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("927 %1.0u%1.4u", -1, 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("927 %1.0u%1.4u", -1, 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("928 %-10.u", 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("928 %-10.u", 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("929 %-3.u%1.4u", 0, -1);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("929 %-3.u%1.4u", 0, -1);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	i = ft_printf("s10 %01.u", 0);
	printf("%s", "uu\n");
	printf("i is %u\n", i);
	j = printf("s10 %01.u", 0);
	printf("%s", "uu\n");
	printf("j is %u\n", j);
	printf("--------------------------------------------------\n");
	return (0);
}
