#include "libftprintf.h"

int ft_printf(const char *ptr, ...);

int main()
{
	int i;
	int j;

	i = ft_printf("s1 %*.*u", 20, 10, 15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s1 %*.*u", 20, 10, 15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*.*u", 20, 10, -15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s2 %*.*u", 20, 10, -15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*.*u", 20, -10, -15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s3 %*.*u", 20, -10, -15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*.*u", -20, -10, -15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s4 %*.*u", -20, -10, -15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*.*u", -20, 10, -15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s5 %*.*u", -20, 10, -15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*.*u", -20, 10, 15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s6 %*.*u", -20, 10, 15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*.*u", -20, -10, 15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s7 %*.*u", -20, -10, 15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %*.*u", 20, -10, 15);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s8 %*.*u", 20, -10, 15);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s9 %*.*u", 0, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s9 %*.*u", 0, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s10 %*.*u", 10, 20, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s10 %*.*u", 10, 20, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s11 %*.*u", 120, -110, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s11 %*.*u", 120, -110, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s12 %*.*u", -20, -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s12 %*.*u", -20, -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s14 %*.*u", 20, -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s14 %*.*u", 20, -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s15 %*.*u", 0, 20, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s15 %*.*u", 0, 20, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s16 %*.*u", 0, 20, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s16 %*.*u", 0, 20, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s17 %*.*u", 0, -20, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s17 %*.*u", 0, -20, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s18 %*.*u", 0, -20, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s18 %*.*u", 0, -20, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s19 %0*.u", 10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s19 %0*.u", 10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s20 %0*.u", 10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s20 %0*.u", 10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s21 %0*.u", -10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s21 %0*.u", -10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s22 %0*.u", -10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s22 %0*.u", -10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s23 %0*.u", 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s23 %0*.u", 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s24 %0*.u", 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s24 %0*.u", 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s25 %0*.u", 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s25 %0*.u", 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s26 %0*.u", 10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s26 %0*.u", 10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s27 %0*.u", -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s27 %0*.u", -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s28 %.*u", 10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s28 %.*u", 10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s29 %.*u", 10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s29 %.*u", 10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s30 %.*u", -10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s30 %.*u", -10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s31 %.*u", -10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s31 %.*u", -10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s32 %.*u", 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s32 %.*u", 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s33 %.*u", 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s33 %.*u", 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s34 %.*u", 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s34 %.*u", 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s35 %.*u", 10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s35 %.*u", 10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s36 %.*u", -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s36 %.*u", -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s37 %*.u", 10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s37 %*.u", 10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s38 %*.u", 10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s38 %*.u", 10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s39 %*.u", -10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s39 %*.u", -10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s40 %*.u", -10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s40 %*.u", -10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s41i %*.u", 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s41i %*.u", 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s41 %*.u", 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s41 %*.u", 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s42 %*.u", 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s42 %*.u", 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s43 %*.u", 10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s43 %*.u", 10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s44 %*.u", -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s44 %*.u", -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s45 %-*.u", 10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s45 %-*.u", 10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s46 %-*.u", 10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s46 %-*.u", 10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s47 %-*.u", -10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s47 %-*.u", -10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s48 %-*.u", -10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s48 %-*.u", -10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s49 %-*.u", 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s49 %-*.u", 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s50 %-*.u", 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s50 %-*.u", 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s51 %-*.u", 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s51 %-*.u", 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s52 %-*.u", 10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s52 %-*.u", 10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s53 %-*.u", -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s53 %-*.u", -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s54 %-*u", 10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s54 %-*u", 10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s55 %-*u", 10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s55 %-*u", 10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s56 %-*u", -10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s56 %-*u", -10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s57 %-*u", -10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s57 %-*u", -10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s58 %-*u", 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s58 %-*u", 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s59 %-*u", 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s59 %-*u", 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s60 %-*u", 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s60 %-*u", 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s61 %-*u", 10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s61 %-*u", 10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s62 %-*u", -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s62 %-*u", -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s63 %0*u", 10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s63 %0*u", 10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s64 %0*u", 10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s64 %0*u", 10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s65 %0*u", -10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s65 %0*u", -10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s66 %0*u", -10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s66 %0*u", -10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s67 %0*u", 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s67 %0*u", 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s68 %0*u", 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s68 %0*u", 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s69 %0*u", 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s69 %0*u", 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s70 %0*u", 10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s70 %0*u", 10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s1 %*u", 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s1 %*u", 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*u", 10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s2 %*u", 10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*u", 10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s3 %*u", 10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*u", -10, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s4 %*u", -10, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*u", -10, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s5 %*u", -10, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*u", 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s6 %*u", 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*u", 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s7 %*u", 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %*u", 10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s8 %*u", 10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s9 %*u", -10, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s9 %*u", -10, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s10 %000010u", 5);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s10 %000010u", 5);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("ss1 %0*.*u", 10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss1 %0*.*u", 10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss2 %0*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss2 %0*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss3 %0*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss3 %0*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss4 %0*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss4 %0*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss5 %0*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss5 %0*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss6 %0*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss6 %0*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss7 %0*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss7 %0*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss8 %0*.*u", 10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss8 %0*.*u", 10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss9 %0*.*u", 0, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss9 %0*.*u", 0, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss10 %0*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss10 %0*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss11 %0*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss11 %0*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss12 %0*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss12 %0*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss14 %0*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss14 %0*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss15 %0*.*u", 0, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss15 %0*.*u", 0, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss16 %0*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss16 %0*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss17 %0*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss17 %0*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("ss18 %0*.*u", 0, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("ss18 %0*.*u", 0, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s1 %-*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s1 %-*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %-*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s2 %-*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %-*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s3 %-*.*u", 10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %-*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s4 %-*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %-*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s5 %-*.*u", -10, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %-*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s6 %-*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %-*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s7 %-*.*u", -10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %-*.*u", 10, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s8 %-*.*u", 10, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s9 %-*.*u", 0, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s9 %-*.*u", 0, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s10 %-*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s10 %-*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s11 %-*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s11 %-*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s12 %-*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s12 %-*.*u", -10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s14 %-*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s14 %-*.*u", 10, 0, 0);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s15 %-*.*u", 0, 0, 10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s15 %-*.*u", 0, 0, 10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s16 %-*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s16 %-*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s17 %-*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s17 %-*.*u", 0, 0, -10);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s18 %*.*u", 0, 0, -111);
	printf("%s", "XX\n");
	printf("i is %u\n", i);
	j = printf("s18 %*.*u", 0, 0, -111);
	printf("%s", "XX\n");
	printf("j is %u\n", j);
	return (0);
}
