#include "libftprintf.h"

int ft_printf(const char *ptr, ...);

int main()
{
	int i;
	int j;

	i = ft_printf("s1 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s1 %*.*d", 10, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s2 %*.*d", 10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*.*d", 10, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s3 %*.*d", 10, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*.*d", -10, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s4 %*.*d", -10, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*.*d", -10, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s5 %*.*d", -10, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*.*d", -10, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s6 %*.*d", -10, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s7 %*.*d", -10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s8 %*.*d", 10, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s9 %*.*d", 0, 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s9 %*.*d", 0, 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s10 %*.*d", 10, 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s10 %*.*d", 10, 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s11 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s11 %*.*d", -10, 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s12 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s12 %*.*d", -10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s14 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s14 %*.*d", 10, -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s15 %*.*d", 0, 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s15 %*.*d", 0, 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s16 %*.*d", 0, 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s16 %*.*d", 0, 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s17 %*.*d", 0, -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s17 %*.*d", 0, -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s18 %*.*d", 0, -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s18 %*.*d", 0, -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s19 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s19 %0*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s20 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s20 %0*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s21 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s21 %0*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s22 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s22 %0*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s23 %0*.d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s23 %0*.d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s24 %0*.d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s24 %0*.d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s25 %0*.d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s25 %0*.d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s26 %0*.d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s26 %0*.d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s27 %0*.d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s27 %0*.d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s28 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s28 %.*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s29 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s29 %.*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s30 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s30 %.*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s31 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s31 %.*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s32 %.*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s32 %.*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s33 %.*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s33 %.*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s34 %.*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s34 %.*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s35 %.*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s35 %.*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s36 %.*d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s36 %.*d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s37 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s37 %*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s38 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s38 %*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s39 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s39 %*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s40 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s40 %*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s41i %*.d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s41i %*.d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s41 %*.d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s41 %*.d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s42 %*.d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s42 %*.d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s43 %*.d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s43 %*.d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s44 %*.d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s44 %*.d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s45 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s45 %-*.d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s46 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s46 %-*.d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s47 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s47 %-*.d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s48 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s48 %-*.d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s49 %-*.d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s49 %-*.d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s50 %-*.d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s50 %-*.d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s51 %-*.d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s51 %-*.d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s52 %-*.d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s52 %-*.d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s53 %-*.d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s53 %-*.d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s54 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s54 %-*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s55 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s55 %-*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s56 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s56 %-*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s57 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s57 %-*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s58 %-*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s58 %-*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s59 %-*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s59 %-*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s60 %-*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s60 %-*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s61 %-*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s61 %-*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s62 %-*d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s62 %-*d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s63 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s63 %0*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s64 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s64 %0*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s65 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s65 %0*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s66 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s66 %0*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s67 %0*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s67 %0*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s68 %0*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s68 %0*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s69 %0*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s69 %0*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s70 %0*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s70 %0*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s1 %*d", 0, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s1 %*d", 0, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s2 %*d", 10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s2 %*d", 10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s3 %*d", 10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s3 %*d", 10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s4 %*d", -10, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s4 %*d", -10, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s5 %*d", -10, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s5 %*d", -10, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s6 %*d", 0, 10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s6 %*d", 0, 10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s7 %*d", 0, -10);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s7 %*d", 0, -10);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s8 %*d", 10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s8 %*d", 10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("-------------------------------------------------\n");
	i = ft_printf("s9 %*d", -10, 0);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s9 %*d", -10, 0);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");
	i = ft_printf("s10 %000010d", 5);
	printf("%s", "XX\n");
	printf("i is %d\n", i);
	j = printf("s10 %000010d", 5);
	printf("%s", "XX\n");
	printf("j is %d\n", j);
	printf("---------------------------------------------------\n");

}
